site_name: Surge-Collapse Training with Entropy Dynamics
theme:
  name: material
nav:
  - Home: index.md
  - About: about.md
  - Model Architecture: model_architecture.md
  - Surge-Collapse Training: surge_collapse_training.md
  - Experiments: experiments.md
  - Results Visualization: results_visualization.md
  - Use Cases: use_cases.md
  - Next Steps: next_steps.md
  - Contributions: contributions.md
  - References: references.md
repo_url: https://github.com/your-username/your-repo
repo_name: GitHub
edit_uri: edit/main/docs/
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
